#!/usr/bin/env python3
"""Generate _fallback_generated.py from capabilities-cache.json.

Usage:
    # From live cache (editor must have run):
    uv run python scripts/sync_fallback.py

    # From test fixture (no editor needed):
    uv run python scripts/sync_fallback.py --from-fixture

    # From arbitrary path:
    uv run python scripts/sync_fallback.py --cache path/to/cache.json

    # Check mode (CI — exits non-zero if output would change):
    uv run python scripts/sync_fallback.py --from-fixture --check
"""

from __future__ import annotations

import argparse
import ast
import json
import pprint
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
MCP_ROOT = SCRIPT_DIR.parent
SRC_DIR = MCP_ROOT / "src" / "cortex_mcp"
FIXTURE_PATH = MCP_ROOT / "tests" / "fixtures" / "capabilities_cache_full.json"

# Walk up from MCP/ to find project root (contains Saved/)
PROJECT_ROOT = MCP_ROOT.parent.parent.parent  # MCP -> UnrealCortex -> Plugins -> ProjectRoot
LIVE_CACHE = PROJECT_ROOT / "Saved" / "Cortex" / "capabilities-cache.json"

OUTPUT_PATH = SRC_DIR / "_fallback_generated.py"


def _normalize_command(cmd: dict) -> dict:
    """Extract only the fields needed for fallback from a cache command entry."""
    result: dict = {"name": cmd["name"]}
    params = cmd.get("params")
    if params:
        result["params"] = [
            {"name": p["name"], "type": p.get("type", "any"), "required": p.get("required", False)}
            for p in params
        ]
    return result


def generate(cache_path: Path) -> str:
    """Read cache JSON, return generated Python source with structured data."""
    data = json.loads(cache_path.read_text(encoding="utf-8"))
    domains = data.get("domains", {})

    total_cmds = sum(len(d.get("commands", [])) for d in domains.values())

    # Build the structured dict
    fallback: dict[str, list[dict]] = {}
    for domain_name in sorted(domains):
        domain_info = domains[domain_name]
        commands = domain_info.get("commands", [])
        fallback[domain_name] = [_normalize_command(cmd) for cmd in commands]

    # Format as Python source using pprint (handles booleans natively)
    formatted = pprint.pformat(fallback, indent=4, width=100)

    lines = [
        '"""Auto-generated fallback commands \u2014 DO NOT EDIT.',
        "",
        "Generated by: scripts/sync_fallback.py",
        f"Source: {cache_path.name}",
        f"Domains: {len(domains)}",
        f"Commands: {total_cmds}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f"FALLBACK_COMMANDS: dict[str, list[dict]] = {formatted}",
        "",
    ]
    source = "\n".join(lines)

    return source


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate fallback commands from capabilities cache")
    source_group = parser.add_mutually_exclusive_group()
    source_group.add_argument("--from-fixture", action="store_true", help="Use test fixture instead of live cache")
    source_group.add_argument("--cache", type=Path, help="Path to capabilities-cache.json")
    parser.add_argument("--check", action="store_true", help="Check mode: exit non-zero if output would change (for CI)")
    args = parser.parse_args()

    if args.cache:
        cache_path = args.cache
    elif args.from_fixture:
        cache_path = FIXTURE_PATH
    else:
        cache_path = LIVE_CACHE

    if not cache_path.is_file():
        print(f"Error: Cache not found at {cache_path}", file=sys.stderr)
        if cache_path == LIVE_CACHE:
            print("Hint: Run the Unreal Editor once to generate the cache, or use --from-fixture", file=sys.stderr)
        sys.exit(1)

    new_source = generate(cache_path)

    # Syntax check without execution
    try:
        ast.parse(new_source)
    except SyntaxError as exc:
        print(f"Error: Generated source has syntax error: {exc}", file=sys.stderr)
        sys.exit(1)

    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"FAIL: {OUTPUT_PATH.relative_to(MCP_ROOT)} does not exist. Run without --check to generate.", file=sys.stderr)
            sys.exit(1)
        existing = OUTPUT_PATH.read_text(encoding="utf-8")
        if existing == new_source:
            print(f"OK: {OUTPUT_PATH.relative_to(MCP_ROOT)} is up to date")
            sys.exit(0)
        else:
            print(f"FAIL: {OUTPUT_PATH.relative_to(MCP_ROOT)} is out of date. Run without --check to regenerate.", file=sys.stderr)
            sys.exit(1)

    OUTPUT_PATH.write_text(new_source, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(MCP_ROOT)} from {cache_path.name}")
    print("Syntax check: OK")


if __name__ == "__main__":
    main()
