#pragma once

#include "CoreMinimal.h"
#include "CortexEditorPhysicalInput.h"
#include "Framework/Application/IInputProcessor.h"
#include "InputCoreTypes.h"
#include "Templates/Function.h"
#include "Templates/SharedPointer.h"

class FCortexEditorPhysicalInputSession;
class FSlateApplication;
class ICursor;
class SWidget;
struct FKeyEvent;
struct FPointerEvent;

/**
 * Non-consuming capture processor for one physical input session.
 *
 * Every handler observes the exact selected Slate user and input device and returns false:
 * the processor must never consume or alter the human's real input, and it is registered
 * before any consuming (CommonUI) preprocessor. Events generated by this session's own
 * dispatch carry a positive synthetic depth and are observed but never recorded or treated
 * as human interference.
 */
class FCortexEditorPhysicalInputCaptureProcessor : public IInputProcessor
{
public:
	explicit FCortexEditorPhysicalInputCaptureProcessor(FCortexEditorPhysicalInputSession& InSession);
	virtual ~FCortexEditorPhysicalInputCaptureProcessor() override;

	//~ Begin IInputProcessor
	virtual void Tick(const float DeltaTime, FSlateApplication& SlateApp, TSharedRef<ICursor> Cursor) override;
	virtual bool HandleKeyDownEvent(FSlateApplication& SlateApp, const FKeyEvent& InKeyEvent) override;
	virtual bool HandleKeyUpEvent(FSlateApplication& SlateApp, const FKeyEvent& InKeyEvent) override;
	virtual bool HandleMouseMoveEvent(FSlateApplication& SlateApp, const FPointerEvent& MouseEvent) override;
	virtual bool HandleMouseButtonDownEvent(FSlateApplication& SlateApp, const FPointerEvent& MouseEvent) override;
	virtual bool HandleMouseButtonUpEvent(FSlateApplication& SlateApp, const FPointerEvent& MouseEvent) override;
	virtual bool HandleMouseButtonDoubleClickEvent(FSlateApplication& SlateApp, const FPointerEvent& MouseEvent) override;
	virtual bool HandleMouseWheelOrGestureEvent(FSlateApplication& SlateApp, const FPointerEvent& InWheelEvent, const FPointerEvent* InGestureEvent) override;
	virtual const TCHAR* GetDebugName() const override;
	//~ End IInputProcessor

	/** Selected-device/user down state observed even before a capture callback exists. */
	const TSet<FKey>& GetObservedHeldKeys() const;
	const TSet<FKey>& GetObservedHeldButtons() const;
	const TSet<FKey>& GetObservedHeldModifiers() const;

private:
	FCortexEditorPhysicalInputSession& Session;
};

/**
 * Per-session capture bookkeeping.
 *
 * CapturedHeldKeys/Buttons is the human down set recorded only after a fresh attributed Down
 * in this capture epoch; OwnedSyntheticKeys/Buttons is the replay-owned set this session may
 * neutralize; ForeignHeld and ForeignInFlight record presses (including a Down currently
 * inside preprocessor routing) that this operation must never touch.
 */
struct FCortexEditorPhysicalInputCaptureState
{
	/** True once SetCaptureCallback armed the epoch on a neutral target. */
	bool bArmed = false;
	/** True once a foreign against an active replay demanded interruption. */
	bool bInterrupted = false;
	/** True when a recorded event's modifier bits disagreed with captured transitions. */
	bool bInconsistentModifiers = false;
	/** Observed down state, maintained from processor installation even before arming. */
	TSet<FKey> ObservedHeldKeys;
	TSet<FKey> ObservedHeldButtons;
	TSet<FKey> ObservedModifierKeys;
	TSet<FKey> CapturedHeldKeys;
	TSet<FKey> CapturedHeldButtons;
	TSet<FKey> OwnedSyntheticKeys;
	TSet<FKey> OwnedSyntheticButtons;
	TSet<FKey> ForeignHeldKeys;
	TSet<FKey> ForeignHeldButtons;
	TSet<FKey> ForeignInFlight;
	/** The exact synthetic keyboard-focus owner so cleanup never steals a foreign focus. */
	TWeakPtr<SWidget> SyntheticFocusOwner;
	/** Monotonic time the capture epoch started; never persisted as a cross-PC identity. */
	double CaptureEpochSeconds = 0.0;
};
